name 'puppetlabs-stdlib'
version '4.1.0'

author 'puppetlabs'
license 'Apache 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-stdlib'
source 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
summary 'Puppet Module Standard Library'
description 'Standard Library for Puppet Modules'
